name: "SSO - SAML"
iconUrl: "https://static.dotcms.com/assets/icons/apps/saml.png"
allowExtraParameters: true
description: "SAML SSO provides users the ability to authentcate against a centralized IDP/Authentication source such as Azure AD or Google's G Suite'.  For information on how to use this App, see the [online documentation](https://dotcms.com/docs/latest/sso-saml)."


params:
  enable:
    value: true
    hidden: false
    type: "BOOL"
    label: "Enable?"
    hint: "Enable | Disable the SAML Configuration"
    required: true
  idpName:
    value: ""
    hidden: false
    type: "STRING"
    label: "IDP Name"
    hint: "Name for the IDP - for reference"
    required: true
  sPIssuerURL:
    value: ""
    hidden: false
    type: "STRING"
    label: "Service Provider Issuer URL"
    hint: "A Unique Id that is shared with the IDP - usually a fully qualified url, e.g. https://dotcms.com/dotAdmin or https://testing.dotcms.com:8443/dotAdmin"
    required: true
  sPEndpointHostname:
    value: ""
    hidden: false
    type: "STRING"
    label: "Service Provider Endpoint Hostname/Port"
    hint: "e.g. dotcms.com or testing.dotcms.com:8443"
    required: true
  signatureValidationType:
    hidden: false
    type: "SELECT"
    label: "Validation Type"
    hint: "Depends on your IDP Configuration."
    required: true
    value:
      -
        label: "Only Response"
        value: "response"
        selected: true
      -
        label: "Only Assertion"
        value: "assertion"
      -
        label: "Response & Assertion"
        value: "responseandassertion"
  idPMetadataFile:
    value: ""
    hidden: false
    type: "STRING"
    label: "IDP Metadata File"
    hint: "Cut and paste your IDP Metadata File here - this should be valid XML"
    required: true
  publicCert:
    value: ""
    hidden: false
    type: "STRING"
    label: "Public Certifcate"
    hint: "Cut and paste your Public Certificate here"
    required: true
  privateKey:
    value: ""
    hidden: false
    type: "STRING"
    label: "Private Key"
    hint: "Cut and paste your Private Key here"
    required: true





