name: ZenHub link PR to issue
on: pull_request

jobs:
  connect_pr_to_issue:
    runs-on: ubuntu-latest
    name: Connect PR to Issue
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: ZenHub link PR to issue
        uses: coblox/zenhub-link-pr-to-issue@v0.1.1
        with:
#          ZENHUB_TOKEN: ${{ secrets.ZENHUB_TOKEN }}
          ZENHUB_TOKEN: '50982ad6aca1330f4d4220957f63150f21cd235fc1f873def82b2c7610a7b190da651b84f7f1a4da'
